# This workflow will build a .NET project!
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      #      - name: Substitute variables in appsettings.json
      #        run: |
      #          sed -i "s|REPLACE_CONNECTION_STRING|${{ secrets.DB_CONNECTION_STRING }}|g" ${{ github.workspace }}/appsettings.json
      #          cat /home/runner/work/SharedGroceryList-Back-End/SharedGroceryList-Back-End/appsettings.json
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        with:
          organization: "gijsverdonk"
          token: ${{ secrets.SONAR_TOKEN }}
      - name: Analyze with SonarCloud
        run: dotnet sonarscanner begin /k:"gijsverdonk_sgl" /o:"gijsverdonk" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" && dotnet build && dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: gijsver/sharedgrocerylist-back-end:latest
          platforms: linux/amd64
